# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-28 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ASources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('pub_date', models.DateTimeField(db_index=True, verbose_name='date published')),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_parsed', models.BooleanField(db_index=True, default=False, verbose_name='text was parsed?')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.AllTags')),
            ],
        ),
        migrations.CreateModel(
            name='RssChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UrlInText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NewsText',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.News')),
                ('text', models.TextField()),
                ('is_keywords_extracted', models.BooleanField(db_index=True, default=False)),
                ('is_parsed', models.BooleanField(default=False)),
                ('check_tag', models.BooleanField(db_index=True, default=False)),
                ('is_emo_defined', models.BooleanField(db_index=True, default=False)),
                ('is_vectorized', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsVector',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.News')),
                ('vector', models.BinaryField(null=True)),
                ('is_compared', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.AddField(
            model_name='urlintext',
            name='news',
            field=models.ManyToManyField(to='db.News'),
        ),
        migrations.AddField(
            model_name='rsschannels',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Site'),
        ),
        migrations.AddField(
            model_name='news',
            name='related_news',
            field=models.ManyToManyField(related_name='_news_related_news_+', to='db.News'),
        ),
        migrations.AddField(
            model_name='news',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Site'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='news',
            field=models.ManyToManyField(to='db.News'),
        ),
        migrations.AddField(
            model_name='asources',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Site'),
        ),
        migrations.CreateModel(
            name='NewsEmotions',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.NewsText')),
                ('emo_weight', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='newstags',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.NewsText'),
        ),
    ]
