# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ASources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEmotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emo_weight', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='NewsText',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.News')),
                ('text', models.TextField()),
                ('is_keywords_extracted', models.BooleanField(default=False)),
                ('is_parsed', models.BooleanField(default=False)),
                ('check_tag', models.BooleanField(default=False)),
                ('is_emo_defined', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UrlInText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='news',
            name='is_parsed',
            field=models.BooleanField(default=False, verbose_name='text was parsed?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(db_index=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='rsschannels',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AddField(
            model_name='urlintext',
            name='news',
            field=models.ManyToManyField(to='db.News'),
        ),
        migrations.AddField(
            model_name='newstags',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.NewsText'),
        ),
        migrations.AddField(
            model_name='newstags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.AllTags'),
        ),
        migrations.AddField(
            model_name='newsemotions',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.NewsText'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='news',
            field=models.ManyToManyField(to='db.News'),
        ),
        migrations.AddField(
            model_name='asources',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Site'),
        ),
    ]
