# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
