# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20160306_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_name',
            new_name='name',
        ),
    ]
