# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20160307_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rsschannels',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
