# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20160307_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsText',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.News')),
                ('text', models.TextField()),
            ],
        ),
    ]
