# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_newstext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(db_index=True, max_length=300),
        ),
    ]
