# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_newstext'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300)),
                ('news', models.ManyToManyField(to='db.News')),
            ],
        ),
    ]
