# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20160401_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Site')),
            ],
        ),
    ]
