# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.1 on 2016-04-09 06:55
=======
# Generated by Django 1.9.4 on 2016-04-02 17:41
>>>>>>> master
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_asources'),
        ('db', '0006_keyword'),
    ]

    operations = [
    ]
