# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 1
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_asources'),
        ('db', '0006_keyword'),
    ]

    operations = [
    ]
