# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlInText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=300)),
                ('news', models.ManyToManyField(to='db.News')),
            ],
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
