# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20160405_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstext',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
