# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20160405_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_parsed',
            field=models.BooleanField(default=False, verbose_name='text was parsed?'),
        ),
    ]
