# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_news_is_parsed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.News')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.AllTags')),
            ],
        ),
        migrations.AddField(
            model_name='newstext',
            name='check_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=300),
        ),
    ]
