# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20160409_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstext',
            name='is_keywords_extracted',
        ),
    ]
