# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_newstext_is_keywords_extracted'),
        ('db', '0013_auto_20160409_0743'),
    ]

    operations = [
    ]
