# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_remove_newstext_is_keywords_extracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstext',
            name='is_keywords_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
